### ISSUE TITLE
Is it possible to exec a callback after the toast is dismissed?

### ISSUE THREAD

**Issue by onhernandes** [arnnis/react-native-toast-notifications#172]
I'd like to execute a callback after the toast is dismissed (when either user dismiss or after the duration has ended), is it possible? If not, I'd like to try to implement.

Context: I use toast to send notifications before/during/after actions like submitting a form, and then I'd like to send the user to another screen after sometime e.g. when the toast dismisses

**Comment by kevinlam92** [comment]
I was trying to do this as well. It turns out there is an `onHide` function defined in the ToastProps but I don't think its called anywhere. As a workaround, I just created a new type using the `renderType` and made an empty useEffect cleanup function for the callback.

Here is an example:

In `ToastProvider` add a new type `CallbackToast`:

```
<ToastProvider
   renderType={{
      CallbackToast: CallbackToast,
   }}>
        //...
</ToastProvider>
      
const CallbackToast = (toast) => {
  React.useEffect(() => {
    return () => {
      // run callback
      toast.data.onDismiss();
    };
  }, []);

  return <View><Text>Some example toast</Text></View>
}
```

Finally just call `toast.show` normally but in the data pass in the callback you wanted to run. For example:

`toast.show("Hello World", {data: { onDismiss : () => console.log("on dismiss")}})`

This seems to work both when the custom toast dismisses automatically (after a duration) or prematurely swiped away.

**Comment by pritsawa** [comment]
https://www.youtube.com/watch?v=gkMpbbmWX48&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=54

**Comment by arnnis** [comment]
Yes it's possible. you can use onClose.
```
toast.show("message", { onClose: () => {  console.log("toast closed") }  })
```

**Comment by hpelitebook745G2** [comment]
thanks @arnnis but in my case, the [`onClose` is not invoked when toast is closed](https://github.com/arnnis/react-native-toast-notifications/issues/183). please advise.
